# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
