# Generated by Django 5.1.1 on 2024-09-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_remove_quotationitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
    ]
