# Generated by Django 5.1.1 on 2024-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_remove_quotation_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
