# Generated by Django 5.1.1 on 2024-10-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_invoice_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Accounts Recievable', 'Accounts Recievable'), ('Other Current Assets', 'Other Current Assets'), ('Fixed Asset', 'Fixed Asset'), ('Other Asset', 'Other Asset'), ('Other Current Liability', 'Other Current Liability'), ('Long Term Liability', 'Long Term Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Expenses', 'Expenses'), ('Other Income', 'Other Income')], max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('Airtel Money', 'Airtel Money'), ('MTN Money', 'MTN Money'), ('Other', 'Other')], max_length=30, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.category')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.supplier')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
