# Generated by Django 5.1.1 on 2024-10-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_category_supplier_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Accounts Recievable', 'Accounts Recievable'), ('Other Current Assets', 'Other Current Assets'), ('Fixed Asset', 'Fixed Asset'), ('Other Asset', 'Other Asset'), ('Other Current Liability', 'Other Current Liability'), ('Long Term Liability', 'Long Term Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Expenses', 'Expenses'), ('Other Income', 'Other Income')], max_length=100, null=True),
        ),
    ]
