# Generated by Django 5.1.1 on 2024-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_remove_expense_category_name_expense_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
