# Generated by Django 5.1.1 on 2024-10-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_alter_supplier_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Accounts Receivable', 'Accounts Receivable'), ('Current Assets', 'Current Assets'), ('Fixed Assets', 'Fixed Assets'), ('Other Assets', 'Other Assets'), ('Current Liabilities', 'Current Liabilities'), ('Long-Term Liabilities', 'Long-Term Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Operating Expenses', 'Operating Expenses'), ('Administrative Expenses', 'Administrative Expenses'), ('Marketing Expenses', 'Marketing Expenses'), ('Depreciation', 'Depreciation'), ('Miscellaneous Income', 'Miscellaneous Income'), ('Miscellaneous Expenses', 'Miscellaneous Expenses')], max_length=100, null=True),
        ),
    ]
