# Generated by Django 5.1.1 on 2024-10-15 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_expense_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
