# Generated by Django 5.1.1 on 2024-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0011_alter_expense_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
