# Generated by Django 5.1.1 on 2024-10-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0012_receipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='datos.invoice'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
