# Generated by Django 5.1.1 on 2024-10-18 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0013_alter_receipt_invoice_delete_expense_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_type', models.CharField(choices=[('Bank Charge', 'Bank Charge'), ('Current Liabilities', 'Current Liabilities'), ('Long-Term Liabilities', 'Long-Term Liabilities'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Operating Expenses', 'Operating Expenses'), ('Administrative Expenses', 'Administrative Expenses'), ('Marketing Expenses', 'Marketing Expenses'), ('Depreciation', 'Depreciation'), ('Miscellaneous Expenses', 'Miscellaneous Expenses')], max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('Airtel Money', 'Airtel Money'), ('MTN Money', 'MTN Money'), ('Other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.supplier')),
            ],
        ),
    ]
