# Generated by Django 5.1.1 on 2024-10-22 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0014_supplier_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('workstream', models.CharField(choices=[('Revenue', 'Revenue'), ('Regulatory', 'Regulatory'), ('Cost Management', 'Cost Management'), ('Customer Experience', 'Customer Experience'), ('Other', 'Other')], default='BAU', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tpin', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_methods', models.TextField(blank=True, null=True)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_subunit', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='subunit_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='datos.kpi')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='datos.company')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('message', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='datos.task')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='datos.company')),
                ('tasks', models.ManyToManyField(related_name='monthly_reports', to='datos.task')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='datos.company')),
                ('tasks', models.ManyToManyField(related_name='weekly_reports', to='datos.task')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reports', to='datos.company')),
                ('tasks', models.ManyToManyField(related_name='yearly_reports', to='datos.task')),
            ],
        ),
    ]
