# Generated by Django 5.1.1 on 2024-10-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0015_kpi_company_task_reminder_monthlyreport_weeklyreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='airtel_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mtn_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zamtel_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_methods',
            field=models.CharField(choices=[('MTN Money', 'MTN Money'), ('Airtel Money', 'Airtel Money'), ('Zamtel Money', 'Zamtel Money'), ('Bank', 'Bank')], max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.bank'),
        ),
    ]
