# Generated by Django 5.1.1 on 2024-10-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0016_bank_company_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_methods',
        ),
    ]
