# Generated by Django 5.1.1 on 2024-10-22 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0017_remove_company_payment_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='company_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
