# Generated by Django 5.1.1 on 2024-10-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0018_alter_company_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subunit',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='subunit',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='subunit',
        ),
        migrations.RemoveField(
            model_name='yearlyreport',
            name='subunit',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='yearlyreport',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
        migrations.DeleteModel(
            name='YearlyReport',
        ),
    ]
